package com.tbp.visao;

import com.tbp.modelo.*;
import com.tbp.repository.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


@Component
public class Janela extends javax.swing.JFrame {
    
    
    @Autowired
    private EmpresaRepository empresaRepository;
    @Autowired
    private FuncionarioRepository funcionarioRepository;
    
    public Janela() {
        initComponents();  
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        abaCadastroEmpresa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeEmpresa = new javax.swing.JTextField();
        cnpjEmpresa = new javax.swing.JTextField();
        botaoSalvarEmpresa = new javax.swing.JButton();
        abaCadastroFuncionario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoCadastrarNome = new javax.swing.JTextField();
        campoCadastrarCpf = new javax.swing.JTextField();
        campoCadastrarSalario = new javax.swing.JTextField();
        comboCadastrarEmpresa = new javax.swing.JComboBox<>();
        botaoSalvarFuncionario = new javax.swing.JButton();
        abaBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoBusca = new javax.swing.JTextField();
        painelResultados = new javax.swing.JScrollPane();
        botaoBuscar = new javax.swing.JButton();
        abaExibir = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoEditarId = new javax.swing.JTextField();
        campoEditarNome = new javax.swing.JTextField();
        campoEditarCpf = new javax.swing.JTextField();
        campoEditarSalario = new javax.swing.JTextField();
        comboEditarEmpresa = new javax.swing.JComboBox<>();
        botaoEditarFuncionario = new javax.swing.JButton();
        botaoRemoverFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPanelMouseClicked(evt);
            }
        });

        jLabel1.setText("CNPJ:");

        jLabel2.setText("Nome:");

        nomeEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmpresaActionPerformed(evt);
            }
        });

        cnpjEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjEmpresaActionPerformed(evt);
            }
        });

        botaoSalvarEmpresa.setText("Salvar");
        botaoSalvarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroEmpresaLayout = new javax.swing.GroupLayout(abaCadastroEmpresa);
        abaCadastroEmpresa.setLayout(abaCadastroEmpresaLayout);
        abaCadastroEmpresaLayout.setHorizontalGroup(
            abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpjEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(295, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCadastroEmpresaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSalvarEmpresa)
                .addGap(80, 80, 80))
        );
        abaCadastroEmpresaLayout.setVerticalGroup(
            abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cnpjEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(botaoSalvarEmpresa)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        tabPanel.addTab("Cadastro Empresa", abaCadastroEmpresa);

        jLabel3.setText("Nome:");

        jLabel4.setText("CPF:");

        jLabel5.setText("Salario:");

        jLabel6.setText("Empresa:");

        comboCadastrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCadastrarEmpresaActionPerformed(evt);
            }
        });

        botaoSalvarFuncionario.setText("Salvar");
        botaoSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroFuncionarioLayout = new javax.swing.GroupLayout(abaCadastroFuncionario);
        abaCadastroFuncionario.setLayout(abaCadastroFuncionarioLayout);
        abaCadastroFuncionarioLayout.setHorizontalGroup(
            abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroFuncionarioLayout.createSequentialGroup()
                        .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoCadastrarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCadastrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(abaCadastroFuncionarioLayout.createSequentialGroup()
                        .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(abaCadastroFuncionarioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoSalvarFuncionario))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abaCadastroFuncionarioLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(comboCadastrarEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abaCadastroFuncionarioLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)
                                .addComponent(campoCadastrarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(298, Short.MAX_VALUE))))
        );
        abaCadastroFuncionarioLayout.setVerticalGroup(
            abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroFuncionarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoCadastrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoCadastrarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoCadastrarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboCadastrarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoSalvarFuncionario)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        tabPanel.addTab("Cadastro Funcionario", abaCadastroFuncionario);

        abaBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                abaBuscarFocusGained(evt);
            }
        });

        jLabel7.setText("Busca:");

        campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaActionPerformed(evt);
            }
        });

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaBuscarLayout = new javax.swing.GroupLayout(abaBuscar);
        abaBuscar.setLayout(abaBuscarLayout);
        abaBuscarLayout.setHorizontalGroup(
            abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaBuscarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(abaBuscarLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoBuscar)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        abaBuscarLayout.setVerticalGroup(
            abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaBuscarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar))
                .addGap(34, 34, 34)
                .addComponent(painelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tabPanel.addTab("Buscar Funcionario", abaBuscar);

        jLabel8.setText("ID");

        jLabel9.setText("Nome");

        jLabel10.setText("CPF");

        jLabel11.setText("Salario");

        jLabel12.setText("Empresa");

        campoEditarId.setEditable(false);

        botaoEditarFuncionario.setText("Editar");
        botaoEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarFuncionarioActionPerformed(evt);
            }
        });

        botaoRemoverFuncionario.setText("Remover");
        botaoRemoverFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaExibirLayout = new javax.swing.GroupLayout(abaExibir);
        abaExibir.setLayout(abaExibirLayout);
        abaExibirLayout.setHorizontalGroup(
            abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaExibirLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(abaExibirLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboEditarEmpresa, 0, 310, Short.MAX_VALUE))
                    .addGroup(abaExibirLayout.createSequentialGroup()
                        .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(24, 24, 24)
                        .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoEditarSalario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(campoEditarCpf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEditarNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEditarId))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaExibirLayout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(botaoEditarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoRemoverFuncionario)
                .addGap(154, 154, 154))
        );
        abaExibirLayout.setVerticalGroup(
            abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaExibirLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoEditarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoEditarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoEditarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(comboEditarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditarFuncionario)
                    .addComponent(botaoRemoverFuncionario))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tabPanel.addTab("Exibir Funcionario", abaExibir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPanelMouseClicked
        Iterable<Empresa> empresas = empresaRepository.findAll();
        comboCadastrarEmpresa.removeAllItems();        
        for(Empresa empresa : empresas) {
            comboCadastrarEmpresa.addItem(empresa);
        }

    }//GEN-LAST:event_tabPanelMouseClicked

    private void botaoSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarFuncionarioActionPerformed
        String nome = campoCadastrarNome.getText();
        String cpf = campoCadastrarCpf.getText();
        Double salario = Double.parseDouble(campoCadastrarSalario.getText());
        Empresa empresa = (Empresa) comboCadastrarEmpresa.getSelectedItem();
        Funcionario funcionario = new Funcionario(nome,  cpf, salario, empresa);
        funcionarioRepository.save(funcionario);
        JOptionPane.showMessageDialog(null, "Funcionario salvo com sucesso");
        campoCadastrarNome.setText("");
        campoCadastrarCpf.setText("");
        campoCadastrarSalario.setText("");

    }//GEN-LAST:event_botaoSalvarFuncionarioActionPerformed

    private void comboCadastrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCadastrarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCadastrarEmpresaActionPerformed

    private void botaoSalvarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarEmpresaActionPerformed
        String nome = nomeEmpresa.getText();
        String cnpj = cnpjEmpresa.getText();
        Empresa empresa = new Empresa(nome, cnpj);
        empresaRepository.save(empresa);
        JOptionPane.showMessageDialog(null, "Empresa salva com sucesso");

        nomeEmpresa.setText("");
        cnpjEmpresa.setText("");
    }//GEN-LAST:event_botaoSalvarEmpresaActionPerformed

    private void cnpjEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjEmpresaActionPerformed

    private void nomeEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmpresaActionPerformed

    private void campoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        String nome = campoBusca.getText();
        List<Funcionario> funcionarioList = funcionarioRepository.findByNomeIgnoreCaseContaining(nome);
        JList jList = new JList();
        DefaultListModel<Funcionario> listModel = new DefaultListModel();
        for(Funcionario funcionario : funcionarioList) {
            listModel.addElement(funcionario);
        }
        jList.setModel(listModel);
        painelResultados.setViewportView(jList);
        painelResultados.setVisible(true);
        jList.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
              Funcionario f = (Funcionario) jList.getSelectedValue();
              campoEditarId.setText(f.getId() + "");
              campoEditarCpf.setText(f.getCpf());
              campoEditarSalario.setText(f.getSalario() + "");
              campoEditarNome.setText(f.getNome());
              Iterable<Empresa> empresas = empresaRepository.findAll();
              comboEditarEmpresa.removeAllItems();        
              for(Empresa empresa : empresas) {
                  comboEditarEmpresa.addItem(empresa);
                  if(empresa.getId().equals(f.getEmpresa().getId())) {
                      comboEditarEmpresa.setSelectedItem(empresa);
                  }
              }
              tabPanel.setSelectedComponent(abaExibir);
              listModel.clear();
            }            
        });
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarFuncionarioActionPerformed
        Integer id = Integer.parseInt(campoEditarId.getText());
        String nome = campoEditarNome.getText();
        String cpf = campoEditarCpf.getText();
        Double salario = Double.parseDouble(campoEditarSalario.getText());
        Empresa empresa = (Empresa) comboEditarEmpresa.getSelectedItem();
        Funcionario funcionario = new Funcionario(nome,  cpf, salario, empresa);
        funcionario.setId(id);
        funcionarioRepository.save(funcionario);
        JOptionPane.showMessageDialog(null, "Funcionario atualizado com sucesso");
        tabPanel.setSelectedComponent(abaBuscar);
      
    }//GEN-LAST:event_botaoEditarFuncionarioActionPerformed

    private void abaBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_abaBuscarFocusGained
      
    }//GEN-LAST:event_abaBuscarFocusGained

    private void botaoRemoverFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverFuncionarioActionPerformed
        Integer id = Integer.parseInt(campoEditarId.getText());
        funcionarioRepository.deleteById(id);
        tabPanel.setSelectedComponent(abaBuscar);
    }//GEN-LAST:event_botaoRemoverFuncionarioActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaBuscar;
    private javax.swing.JPanel abaCadastroEmpresa;
    private javax.swing.JPanel abaCadastroFuncionario;
    private javax.swing.JPanel abaExibir;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoEditarFuncionario;
    private javax.swing.JButton botaoRemoverFuncionario;
    private javax.swing.JButton botaoSalvarEmpresa;
    private javax.swing.JButton botaoSalvarFuncionario;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JTextField campoCadastrarCpf;
    private javax.swing.JTextField campoCadastrarNome;
    private javax.swing.JTextField campoCadastrarSalario;
    private javax.swing.JTextField campoEditarCpf;
    private javax.swing.JTextField campoEditarId;
    private javax.swing.JTextField campoEditarNome;
    private javax.swing.JTextField campoEditarSalario;
    private javax.swing.JTextField cnpjEmpresa;
    private javax.swing.JComboBox<Empresa> comboCadastrarEmpresa;
    private javax.swing.JComboBox<Empresa> comboEditarEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeEmpresa;
    private javax.swing.JScrollPane painelResultados;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables
}
