package com.tbp.visao;

import com.tbp.modelo.*;
import com.tbp.repository.*;
import com.tbp.service.PizzaService;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


@Component
public class Janela extends javax.swing.JFrame {
    
    
   private PizzaService pizzaService;
        
           
    @Autowired
    public Janela( PizzaService pizzaService) {
        this.pizzaService = pizzaService;
        initComponents();  
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        abaCadastroEmpresa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomePizza = new javax.swing.JTextField();
        precoPizza = new javax.swing.JTextField();
        botaoSalvarPizza = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ingredientesPizza = new javax.swing.JTextField();
        abaCadastroFuncionario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoCadastrarNome = new javax.swing.JTextField();
        campoCadastrarCpf = new javax.swing.JTextField();
        campoCadastrarSalario = new javax.swing.JTextField();
        comboCadastrarEmpresa = new javax.swing.JComboBox<>();
        botaoSalvarFuncionario = new javax.swing.JButton();
        abaBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoBusca = new javax.swing.JTextField();
        painelResultados = new javax.swing.JScrollPane();
        botaoBuscar = new javax.swing.JButton();
        abaExibir = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoEditarId = new javax.swing.JTextField();
        campoEditarNome = new javax.swing.JTextField();
        campoEditarCpf = new javax.swing.JTextField();
        campoEditarSalario = new javax.swing.JTextField();
        comboEditarEmpresa = new javax.swing.JComboBox<>();
        botaoEditarFuncionario = new javax.swing.JButton();
        botaoRemoverFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPanelMouseClicked(evt);
            }
        });

        jLabel1.setText("Ingredientes");

        jLabel2.setText("Nome:");

        nomePizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePizzaActionPerformed(evt);
            }
        });

        precoPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoPizzaActionPerformed(evt);
            }
        });

        botaoSalvarPizza.setText("Salvar");
        botaoSalvarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarPizzaActionPerformed(evt);
            }
        });

        jLabel13.setText("Preço");

        ingredientesPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientesPizzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroEmpresaLayout = new javax.swing.GroupLayout(abaCadastroEmpresa);
        abaCadastroEmpresa.setLayout(abaCadastroEmpresaLayout);
        abaCadastroEmpresaLayout.setHorizontalGroup(
            abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientesPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(botaoSalvarPizza)
                        .addGap(80, 80, 80))
                    .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                        .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13))
                        .addGap(47, 47, 47)
                        .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        abaCadastroEmpresaLayout.setVerticalGroup(
            abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomePizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(botaoSalvarPizza))
                    .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ingredientesPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        tabPanel.addTab("Cadastro Pizza", abaCadastroEmpresa);

        jLabel3.setText("Nome:");

        jLabel4.setText("CPF:");

        jLabel5.setText("Salario:");

        jLabel6.setText("Empresa:");

        comboCadastrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCadastrarEmpresaActionPerformed(evt);
            }
        });

        botaoSalvarFuncionario.setText("Salvar");
        botaoSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroFuncionarioLayout = new javax.swing.GroupLayout(abaCadastroFuncionario);
        abaCadastroFuncionario.setLayout(abaCadastroFuncionarioLayout);
        abaCadastroFuncionarioLayout.setHorizontalGroup(
            abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroFuncionarioLayout.createSequentialGroup()
                        .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoCadastrarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCadastrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(abaCadastroFuncionarioLayout.createSequentialGroup()
                        .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(abaCadastroFuncionarioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoSalvarFuncionario))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abaCadastroFuncionarioLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(comboCadastrarEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abaCadastroFuncionarioLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)
                                .addComponent(campoCadastrarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(298, Short.MAX_VALUE))))
        );
        abaCadastroFuncionarioLayout.setVerticalGroup(
            abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroFuncionarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoCadastrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoCadastrarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoCadastrarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboCadastrarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoSalvarFuncionario)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        tabPanel.addTab("Cadastro Funcionario", abaCadastroFuncionario);

        abaBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                abaBuscarFocusGained(evt);
            }
        });

        jLabel7.setText("Busca:");

        campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaActionPerformed(evt);
            }
        });

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaBuscarLayout = new javax.swing.GroupLayout(abaBuscar);
        abaBuscar.setLayout(abaBuscarLayout);
        abaBuscarLayout.setHorizontalGroup(
            abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaBuscarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(abaBuscarLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoBuscar)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        abaBuscarLayout.setVerticalGroup(
            abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaBuscarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar))
                .addGap(34, 34, 34)
                .addComponent(painelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tabPanel.addTab("Buscar Funcionario", abaBuscar);

        jLabel8.setText("ID");

        jLabel9.setText("Nome");

        jLabel10.setText("CPF");

        jLabel11.setText("Salario");

        jLabel12.setText("Empresa");

        campoEditarId.setEditable(false);

        botaoEditarFuncionario.setText("Editar");
        botaoEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarFuncionarioActionPerformed(evt);
            }
        });

        botaoRemoverFuncionario.setText("Remover");
        botaoRemoverFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaExibirLayout = new javax.swing.GroupLayout(abaExibir);
        abaExibir.setLayout(abaExibirLayout);
        abaExibirLayout.setHorizontalGroup(
            abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaExibirLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(abaExibirLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboEditarEmpresa, 0, 310, Short.MAX_VALUE))
                    .addGroup(abaExibirLayout.createSequentialGroup()
                        .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(24, 24, 24)
                        .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoEditarSalario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(campoEditarCpf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEditarNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEditarId))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaExibirLayout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(botaoEditarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoRemoverFuncionario)
                .addGap(154, 154, 154))
        );
        abaExibirLayout.setVerticalGroup(
            abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaExibirLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoEditarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoEditarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoEditarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(comboEditarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditarFuncionario)
                    .addComponent(botaoRemoverFuncionario))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tabPanel.addTab("Exibir Funcionario", abaExibir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPanelMouseClicked
        // implementar para preencher a combo empresa no cadastro de funcionario

    }//GEN-LAST:event_tabPanelMouseClicked

    private void botaoSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarFuncionarioActionPerformed
        // implementar o salvar funcionario

    }//GEN-LAST:event_botaoSalvarFuncionarioActionPerformed

    private void comboCadastrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCadastrarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCadastrarEmpresaActionPerformed

    private void botaoSalvarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarPizzaActionPerformed
        String nome = nomePizza.getText();
        Double preco = Double.parseDouble(precoPizza.getText());
        String[] ingredientes = ingredientesPizza.getText().split(";");
        List<Composicao> composicaoList = pizzaService.salvarPizza(nome, preco, ingredientes);
        StringBuffer mensagem = new StringBuffer();
        mensagem.append(composicaoList.get(0).getPizza().getNome());
        mensagem.append("\n");
        for(Composicao c : composicaoList) {
            mensagem.append(c.getIngrediente().getNome());
            mensagem.append("\n");
                    
        }
        JOptionPane.showMessageDialog(null, mensagem);
    }//GEN-LAST:event_botaoSalvarPizzaActionPerformed

    private void precoPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoPizzaActionPerformed

    private void nomePizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePizzaActionPerformed

    private void campoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        // TODO implementar a busca de funcionario
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarFuncionarioActionPerformed
        // TODO implementar o editar funcionarios
      
    }//GEN-LAST:event_botaoEditarFuncionarioActionPerformed

    private void abaBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_abaBuscarFocusGained
      
    }//GEN-LAST:event_abaBuscarFocusGained

    private void botaoRemoverFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverFuncionarioActionPerformed
        // implementar o remover funcionario
    }//GEN-LAST:event_botaoRemoverFuncionarioActionPerformed

    private void ingredientesPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientesPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientesPizzaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaBuscar;
    private javax.swing.JPanel abaCadastroEmpresa;
    private javax.swing.JPanel abaCadastroFuncionario;
    private javax.swing.JPanel abaExibir;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoEditarFuncionario;
    private javax.swing.JButton botaoRemoverFuncionario;
    private javax.swing.JButton botaoSalvarFuncionario;
    private javax.swing.JButton botaoSalvarPizza;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JTextField campoCadastrarCpf;
    private javax.swing.JTextField campoCadastrarNome;
    private javax.swing.JTextField campoCadastrarSalario;
    private javax.swing.JTextField campoEditarCpf;
    private javax.swing.JTextField campoEditarId;
    private javax.swing.JTextField campoEditarNome;
    private javax.swing.JTextField campoEditarSalario;
    private javax.swing.JComboBox<String> comboCadastrarEmpresa;
    private javax.swing.JComboBox<String> comboEditarEmpresa;
    private javax.swing.JTextField ingredientesPizza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomePizza;
    private javax.swing.JScrollPane painelResultados;
    private javax.swing.JTextField precoPizza;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables
}
